### ISSUE TITLE
Disk of particles orbit around the Sun

### ISSUE THREAD

**Issue by dayvidpham** [dayvidpham/dhpham-website#3]
## Objective

Have a disk of particles around the Sun/circle! Kind of like Saturn. The disk should be viewed slightly edge-on the viewer, angled slightly downwards.

## Tasks

- [ ] Disk around the Sun
- [ ] Particles possibly circulating, or some coloured points within the disk slowly orbitting around the Sun to show movement
- [ ] Stetch goal: perspective geometry, maybe some kind of fish-eye/wide-angle lens

## Inspiration

Bunch more stuff in this sub-board: https://www.pinterest.ca/flyingcow4/website/space/

![2009-astronomy-poster](https://github.com/dayvidpham/dhpham-website/assets/22456875/f15329d6-ec5f-423a-8a7d-ba6fb55bad6f)
![2010-astronomy-poster-simon-cage](https://github.com/dayvidpham/dhpham-website/assets/22456875/6d3122ba-b948-42ea-a03f-32184d68e0e8)
